version: "3"
services:
  db_tests:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
  app_tests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure

    